# QuantMini Data Lake Path Configuration
#
# This file centralizes all data lake path configuration.
# Switch between production and test environments by changing the 'active_environment' setting.
#
# Usage:
#   - Set 'active_environment' to 'production' or 'test'
#   - All pipeline components will automatically use the correct paths
#   - No code changes needed to switch environments

# Active environment: 'production' or 'test'
active_environment: production

# Production environment paths
production:
  # Main data lake root (Medallion Architecture) - External SSD
  data_lake_root: /Volumes/990EVOPLUS/quantlake

  # Explicit layer paths (optional - will use data_lake_root/<layer> if not specified)
  landing_path: /Volumes/990EVOPLUS/quantlake/landing
  bronze_path: /Volumes/990EVOPLUS/quantlake/bronze
  silver_path: /Volumes/990EVOPLUS/quantlake/silver
  gold_path: /Volumes/990EVOPLUS/quantlake/gold

  # Metadata and logs
  metadata_path: /Volumes/990EVOPLUS/quantlake/metadata
  logs_path: /Volumes/990EVOPLUS/quantlake/logs

# Test environment paths (for development/testing)
test:
  # Test data lake (usually smaller, local storage)
  data_lake_root: /Users/zheyuanzhao/workspace/quantmini/data/test-lake

  # Test layer paths
  bronze_path: /Users/zheyuanzhao/workspace/quantmini/data/test-lake/bronze
  silver_path: /Users/zheyuanzhao/workspace/quantmini/data/test-lake/silver
  gold_path: /Users/zheyuanzhao/workspace/quantmini/data/test-lake/gold

  # Test metadata and logs
  metadata_path: /Users/zheyuanzhao/workspace/quantmini/data/test-lake/metadata
  logs_path: /Users/zheyuanzhao/workspace/quantmini/data/test-lake/logs

# Environment aliases (for quick reference)
environments:
  prod: production
  dev: test
  staging: test
  local: test

# Path validation rules
validation:
  # Require data_lake_root to be an absolute path
  require_absolute_paths: true

  # Create directories if they don't exist
  auto_create_directories: true

  # Minimum free space required (in GB)
  min_free_space_gb: 50
