name: Tests

on:
  push:
    branches: [ main, develop, claude/* ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Create config directory
        run: |
          mkdir -p config
          cp config/credentials.yaml.example config/credentials.yaml || echo "No credentials example found"
          cp config/system_profile.yaml.example config/system_profile.yaml || echo "No system profile example found"

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest tests/unit/ -v --tb=short

      - name: Run integration tests
        run: |
          source .venv/bin/activate
          pytest tests/integration/ -v --tb=short
        continue-on-error: true  # Integration tests may require external resources

      - name: Generate coverage report
        if: matrix.python-version == '3.11'
        run: |
          source .venv/bin/activate
          pytest tests/unit/ --cov=src --cov-report=xml --cov-report=html --cov-report=term

      - name: Upload coverage report
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
